### ISSUE TITLE
Remove ggplot and ggalt dependencies 

### ISSUE THREAD

**Issue by kauebraga** [ipeaGIT/acesso_app#13]
RIght now, `ggplot `and `ggalt` are imported only to generate plots when the user wants to export one of the figures in the graphs tab.
I think we can avoid these dependencies by pre-generating all the possible plots and making they available via download

**Comment by rafapereirabr** [comment]
is this a good idea? There are hundreds and hundreds of possible charts. Does importing ggplot put such a big computational cost?

**Comment by kauebraga** [comment]
I found a better way (I guess): the application now only loads ggplot and ggalt if the user clicks in the download button (4560f62d2ab65ce2bfb8e83a3e58ce39e22142b3. We should be fine now.
