### ISSUE TITLE
Fixed min max scale across years

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/acesso_app#16]
•	A escala de cores (mix – max) fica constante entre os anos para os gráficos de uso do solo. Seria uma boa fazer igual para acessibilidade. Isso ajuda a ver melhor a mudança entre os anos

**Comment by kauebraga** [comment]
Done at https://github.com/ipeaGIT/acesso_app/commit/f672a9019d86e90b2b347db1ca59b354fc0c8d8c
