### ISSUE TITLE
Mode icon and year

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/acesso_app#17]
•	O painel mostra ônibus nos anos disponíveis. Mas o carro só esta disponível em 2019 e isso não fica claro

**Comment by kauebraga** [comment]
Criei um popup ao lado da seleção do modo que diz:

pt-br: <ul><li><strong>Transporte público:</strong> tempos de viagem são calculados a partir da rede de transporte público presente no GTFS de cada cidade ao final de cada ano</li><li><strong>Carro:</strong> tempos de viagem são calculados a partir velocidades médias das vias coletadas entre 2018 e 2019, únicos para todos os anos</li></ul>

en: <ul><li><strong>Public transport:</strong> travel times are calculated based on the public transport network presented at each city's GTFS at the end of each year</li><li><strong>Car:</strong> travel times are calculated based on mean network speeds from 2018 and 2019, same for every year</li></ul>

Sugestões são bem vindas!

**Comment by rafapereirabr** [comment]
sugestão abaixo:

pt-br: <ul><li><strong>Transporte público:</strong> tempos de viagem calculados a partir dos dados de transporte público GTFS de cada cidade em Out. de cada ano</li><li><strong>Carro:</strong> tempos de viagem calculados a partir velocidades médias das vias coletadas entre 2018 e 2019 (único para todos os anos)</li></ul>

en: <ul><li><strong>Public transport:</strong> travel times calculated using GTFS data of each city in Oct of each year</li><li><strong>Car:</strong> travel times calculated based on average road network speeds between 2018 and 2019 (single estimate for entire period)</li></ul>
