### ISSUE TITLE
Create tab with interactive plots

### ISSUE THREAD

**Issue by kauebraga** [ipeaGIT/acesso_app#2]
Create a new tab with interactive plots that [maybe] takes the same inputs as the map takes. Plots should be similar to what we've done on the TD. Additionally:
- Plot with the cumulative distribution of accessibility with the population on the x axis. [Code is already available here](https://github.com/ipeaGIT/acesso_app/blob/5582a61070b2e5bfb2662a583caadf377a2378a8/atlasacessibilidade/server.R#L583)];
- Basic histogram of the variable selected on the map [should this be on a panel on the left side of the map?]

**Comment by kauebraga** [comment]
Checklist:
- [x] Add dumbbell plot;
- [x] Add palma by income and color; 
- [x] Put values on the graphs bars;
- [x] Change graphs colors to IPEA's;
- [x] Add option to export plot (maybe with some modaldialog showing up to expand options);
- [x] Increase the width of the sidebar panel on the graphs panel;
- [x] Make `home` tab unavailable on the navbar; 
- [x] Translate navbar;
- [x] Add title and subtitle (with a short explanation) to graphics;
- [x] Add title, subtitle and legend to the exported graphic;
- [x] Match navbar style to the same style on the website
- [x] Fix title so it can be readable; 
- [x] Translate `title` and `subtitle` (both from the app plot and the exported plot); - (https://github.com/ipeaGIT/acesso_app/commit/59f3bfdbd03bb8fd49ce1a8a85d1008c2733237d)
- [x] Translate `columns` and `attributes names` on the exported csv file (https://github.com/ipeaGIT/acesso_app/commit/de1baff123cc2206c3deaa6d153da696275776f0)
- [x] Adjust the output filename to fit the language (https://github.com/ipeaGIT/acesso_app/commit/de1baff123cc2206c3deaa6d153da696275776f0)

**Comment by kauebraga** [comment]
Add boxplot:
 - User selects the plot, then can select three cities with `shinyWidgets:pickerInput` with `multiple = TRUE` and `options = list(maxItems = 3)` (how can we make sure that cities have similar size?) 
- Then user selects `mode`, `activity` and `time threshold`

**Comment by kauebraga** [comment]
- [x] Delete boxplot from graphs options (closed at  https://github.com/ipeaGIT/acesso_app/commit/6d5621927b695c8144874a555abe967488bb1c2e)
- [x] Delete the option to choose the accessibility indicator (https://github.com/ipeaGIT/acesso_app/commit/75bf0214d4470ad65428c7db35aee3cdcf9f02eb)
- [x] Add a brief explanation for each plot type (77d253343e68f22a4c6cdf1ce162af5d7880dd45)
- [x] Add link to `Texto para Discussao` and `data dictionary` to check for more information (567c26e97a871a8504a59816a44460d1d934e5d2)

**Comment by kauebraga** [comment]
### Improve home page
- [ ] Add basic information about the app;
- [ ] Add logo

**Comment by rafapereirabr** [comment]
Vou conversar com Bernarndo e ver se cosneguimos decidir a logo hoje

**Comment by kauebraga** [comment]
Acho que a gente pode transformar isso em outra issue e fechar essa!
