### ISSUE TITLE
Prepare app shiny.rstudio 

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/acesso_app#5]
- [x] Translate documentation [@kauebraga , @rafapereirabr ]
- [x] Organize and clean code [@kauebraga , [@rafapereirabr ] (f3d3d471581c26b46f6fbce619d88cdde9d6fb3f, da0cacc0ac7a70261850aa1399d497a134c277a8)
- [x] Break down `server.R` in multiple files for easier reading (94da6ca05a6a890686d8f89ffc3faf1e57237e14)
- [x] deploy app on shiny app account [@kauebraga ]

**Comment by kauebraga** [comment]
https://blog.rstudio.com/2020/02/12/shiny-contest-2020-is-here/

**Comment by rafapereirabr** [comment]
Quer fechar esse aqui ? :)
