### ISSUE TITLE
Improve home (landing) page

### ISSUE THREAD

**Issue by kauebraga** [ipeaGIT/acesso_app#8]
- [x] Add basic information about the app;
- [x] Add logo

**Comment by rafapereirabr** [comment]
Ja pode adicionar a logo na pagina de entrada do App. Ainda da para fazer essa modificacao para o concurso do Shiny ?

**Comment by kauebraga** [comment]
Mostly done ai c584317aefd5256cc93a7ba8e9c987b6c8222c2a
